version: '3.5'
networks:
  selenoid:
    external:
      name: selenoid
services:
  mysql:
    networks:
      selenoid: null
    image: mysql:5.7
    command: --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION" --max_connections=1500
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin_pass'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
